# Generated by Django 5.0 on 2024-01-06 13:36

import code_editor.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.CharField(default='cf4f6386f4e946c58ba43fb8203521bf', max_length=200, primary_key=True, serialize=False)),
                ('content', models.JSONField(default=code_editor.models.defaultJson)),
            ],
        ),
        migrations.CreateModel(
            name='WhiteBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_editor.editor')),
            ],
        ),
    ]
